[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'bluz71/vim-nightfly-guicolors'
hook_add = '''
    if !has("gui")
        let g:nightflyTransparent = 1
    endif
'''

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'
hook_add = 'source ~/.vim/rc/coc.rc.vim'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = 'source ~/.vim/rc/denite.rc.vim'

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = 'source ~/.vim/rc/defx.rc.vim'
depends = ['defx-git', 'defx-icons']

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
    let g:indentLine_faster = 1
'''

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
    let g:EasyMotion_leader_key = '<Space><Space>'
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.vim/rc/lightline.rc.vim'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if = '!has("nvim")'

[[plugins]]
repo = 'roxma/nvim-yarp'
on_if = '!has("nvim")'
