[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css']
hook_add = '''
    let g:user_emmet_leader_key=v:null
    autocmd FileType html,css,php imap <buffer><expr><tab>
        \ emmet#isExpandable() ? "\<plug>(emmet-expand-abbr)" :
        \ "\<tab>"
'''

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']
hook_add = '''
    let g:vim_json_syntax_conceal = 0
'''

[[plugins]]
repo = 'PProvost/vim-ps1'
on_ft = ['ps1']

[[plugins]]
repo = 'goerz/jupytext.vim'
on_path = '\.ipynb$'
hook_source = '''
    let g:jupytext_fmt = 'py:percent'
    let g:jupytext_filetype_map = {'py': 'python'}
'''

[[plugins]]
repo = 'jupyter-vim/jupyter-vim'
on_path = '\.ipynb$'

[[plugins]]
repo = 'cohama/lexima.vim'
on_event = 'InsertEnter'

[[plugins]]
repo = 'tyru/caw.vim'
on_event = 'CursorHold'

[[plugins]]
repo = 'machakann/vim-sandwich'
on_event = 'CursorHold'

[[plugins]]
repo = 'easymotion/vim-easymotion'
on_map = '<Plug>(easymotion-prefix)'
hook_add = '''
    map <Space><Space> <Plug>(easymotion-prefix)
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
on_event = 'BufRead'
depends = 'context_filetype.vim'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_if = 'has("nvim")'
on_event = 'BufRead'
hook_post_update = 'TSUpdate'
hook_source = '''
lua << EOF
require'nvim-treesitter.configs'.setup {
    highlight = {
        enable = true,
        additional_vim_regex_highlighting = false
    }
}
EOF
'''

[[plugins]]
repo = 'mattn/vim-notification'
if = '!has("nvim")'

[[plugins]]
repo = 'rcarriga/nvim-notify'
on_if = 'has("nvim")'
on_event = 'VimEnter'
hook_source = '''
lua << EOF
require("notify").setup({
    background_colour = "#000000"
})
EOF
'''
