[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'haishanh/night-owl.vim'

[[plugins]]
repo = 'gosukiwi/vim-atom-dark'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'
hook_add = 'source ~/.vim/rc/coc.rc.vim'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = 'source ~/.vim/rc/denite.rc.vim'

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = 'source ~/.vim/rc/defx.rc.vim'
depends = ['defx-git', 'defx-icons']

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
    let g:indentLine_faster = 1
'''

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'tpope/vim-surround'
hook_add = '''
    let g:surround_{char2nr("「")} = "「 \r 」"
    let g:surround_{char2nr("」")} = "「\r」"
    let g:surround_{char2nr("【")} = "【 \r 】"
    let g:surround_{char2nr("】")} = "【\r】"
    let g:surround_{char2nr("（")} = "（ \r ）"
    let g:surround_{char2nr("）")} = "（\r）"
    let g:surround_{char2nr("＜")} = "＜ \r ＞"
    let g:surround_{char2nr("＞")} = "＜\r＞"
    let g:surround_{char2nr("｛")} = "｛ \r ｝"
    let g:surround_{char2nr("｝")} = "｛\r｝"
'''

[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = '''
    " コメント前にスペースを入れたくない言語
    " au FileType vim,zsh,css,php,cs let g:tcomment#options = {'whitespace': 'no'}
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.vim/rc/lightline.rc.vim'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if = '!has("nvim")'

[[plugins]]
repo = 'roxma/nvim-yarp'
on_if = '!has("nvim")'
