[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css']
hook_add = '''
    let g:user_emmet_leader_key=v:null
    autocmd FileType html,css,php imap <buffer><expr><tab>
        \ emmet#isExpandable() ? "\<plug>(emmet-expand-abbr)" :
        \ "\<tab>"
'''

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']
hook_add = '''
    let g:vim_json_syntax_conceal = 0
'''

[[plugins]]
repo = 'PProvost/vim-ps1'
on_ft = ['ps1']
