[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_event = ['BufReadPost', 'BufNewFile']
on_cmd = ['LspInfo', 'LspInstall', 'LspUninstall']
lua_source = '''
    local nvim_lsp = require('lspconfig')
    local capabilities = require("ddc_source_lsp").make_client_capabilities()

    nvim_lsp.dartls.setup({
        capabilities = capabilities,
    })
'''

[[plugins]]
repo = 'williamboman/mason.nvim'
depends = 'nvim-lspconfig'
on_event = 'FileType'
on_cmd = 'Mason'
lua_source = '''
    require('mason').setup({
        ui = {
            border = "single",
        }
    })
'''

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
on_source = 'nvim-lspconfig'
depends = ['mason.nvim', 'ddc-source-lsp']
lua_source = '''
    require("mason-lspconfig").setup()
    require('mason-lspconfig').setup_handlers({
        function(server_name)
            local nvim_lsp = require('lspconfig')
            local capabilities = require("ddc_source_lsp").make_client_capabilities()
            local opts = {
                capabilities = capabilities,
            }

            nvim_lsp[server_name].setup(opts)
        end
    })
'''

[[plugins]]
repo = 'nvimtools/none-ls.nvim'
on_source = 'nvim-lspconfig'
depends = 'plenary.nvim'
lua_source = '''
    local null_ls = require("null-ls")
    local augroup = vim.api.nvim_create_augroup("LspFormatting", {})
    null_ls.setup {
        sources = {
            require("none-ls.diagnostics.eslint"),
            require("none-ls.code_actions.eslint"),
            null_ls.builtins.formatting.prettier,
        },
        on_attach = function(client, bufnr)
            if client.supports_method("textDocument/formatting") then
                vim.api.nvim_clear_autocmds({ group = augroup, buffer = bufnr })
                vim.api.nvim_create_autocmd("BufWritePre", {
                    group = augroup,
                    buffer = bufnr,
                    callback = function()
                        vim.lsp.buf.format({ async = false })
                    end,
                })
            end
        end,
    }
'''

[[plugins]]
repo = 'nvimtools/none-ls-extras.nvim'
on_source = 'none-ls.nvim'
