[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_event = ['BufReadPost', 'BufNewFile']
on_cmd = ['LspInfo', 'LspInstall', 'LspUninstall']
depends = ['lazydev.nvim']
lua_source = '''
    local nvim_lsp = require('lspconfig')

    -- dartls
    vim.lsp.enable('dartls')

    -- eslint
    -- Install it with npm i -g vscode-langservers-extracted
    vim.lsp.config('eslint', {
        settings = {
            codeActionOnSave = {
                enable = true,
            }
        }
    })
    vim.lsp.enable('eslint')

    -- ts_ls / denols
    local node_root_dir = nvim_lsp.util.root_pattern("package.json")
    local is_node_repo = node_root_dir(vim.api.nvim_buf_get_name(0)) ~= nil
    if is_node_repo then
        vim.lsp.enable('ts_ls')
    else
        vim.lsp.enable('denols')
    end
'''

[[plugins]]
repo = 'williamboman/mason.nvim'
on_cmd = 'Mason'
lua_source = '''
    require('mason').setup({
        ui = {
            border = "single",
        }
    })
'''

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
on_source = 'nvim-lspconfig'
depends = 'mason.nvim'
lua_source = '''
    require("mason-lspconfig").setup({
        automatic_enable = {
            exclude = {
                "denols",
                "ts_ls"
            }
        }
    })
'''

[[plugins]]
repo = 'nvimtools/none-ls.nvim'
on_source = 'nvim-lspconfig'
depends = 'plenary.nvim'
lua_source = '''
    local null_ls = require("null-ls")
    local augroup = vim.api.nvim_create_augroup("LspFormatting", {})
    null_ls.setup {
        sources = {
            null_ls.builtins.formatting.prettier,
        },
        on_attach = function(client, bufnr)
            if client.supports_method("textDocument/formatting") then
                vim.api.nvim_clear_autocmds({ group = augroup, buffer = bufnr })
                vim.api.nvim_create_autocmd("BufWritePre", {
                    group = augroup,
                    buffer = bufnr,
                    callback = function()
                        vim.lsp.buf.format({ async = false })
                    end,
                })
            end
        end,
    }
'''

[[plugins]]
repo = 'nvimtools/none-ls-extras.nvim'
on_source = 'none-ls.nvim'

[[plugins]]
repo = 'folke/lazydev.nvim'
on_ft = 'lua'
lua_source = '''
    require("lazydev").setup({
        library = {
            { path = "${3rd}/luv/library", words = { "vim%.uv" } },
        }
    })
'''
