[[plugins]]
repo = 'hrsh7th/nvim-cmp'
on_event = ['InsertEnter', 'CmdlineEnter']
hooks_file = '~/.vim/rc/nvim-cmp.hooks.lua'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
on_source = 'nvim-cmp'
lua_source = '''
    vim.lsp.config('*', {
        capabilities = require("cmp_nvim_lsp").default_capabilities()
    })
'''

[[plugins]]
repo = 'hrsh7th/cmp-buffer'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-path'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-cmdline'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-vsnip'
on_source = 'nvim-cmp'
depends = 'vim-vsnip'

[[plugins]]
repo = 'onsails/lspkind.nvim'
on_source = 'nvim-cmp'
