set fsync
set fileformats=unix,dos,mac
set number
set cursorline
set smartindent
set title
set nowrap
set statusline=%{expand('%:p:t')}\ %<[%{expand('%:p:h')}]%=\ %m%r%y%w[%{&fenc!=''?&fenc:&enc}][%{&ff}][%l,%c/%p]
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set ignorecase
set smartcase
set noswapfile
set nobackup
set noundofile
set listchars=tab:\>\-
set list
set termguicolors
