" Remove menu bar
set guioptions-=m
" Remove tool bar
set guioptions-=T
" Remove scroll bar
set guioptions-=r
set guioptions-=R
set guioptions-=l
set guioptions-=L
set guioptions-=b

" font
if has("win64")
    set guifont=HackGen\ Console\ NF:h11
elseif has("mac")
    set guifont=HackGen\ Console\ NF:h16
elseif has("linux")
    set guifont=HackGen\ Console\ NF\ 14
endif

" input method control
set imsearch=0
set iminsert=0

" Change cursor color according to IM status
if has('xim') || has('multi_byte_ime')
    highlight Cursor guifg=NONE guibg=Green
    highlight CursorIM guifg=NONE guibg=Red
endif

" Remember window size and position
let g:save_window_file = expand('~/.vimwinpos')
augroup SaveWindow
    autocmd!
    autocmd VimLeavePre * call s:save_window()
    function! s:save_window()
        let options = [
            \ 'set columns=' . &columns,
            \ 'set lines=' . &lines,
            \ 'winpos ' . getwinposx() . ' ' . getwinposy(),
            \ ]
      call writefile(options, g:save_window_file)
    endfunction
augroup END

if filereadable(g:save_window_file)
    execute 'source' g:save_window_file
endif
